site_name: Desarrollo Web en Entorno Servidor
site_url: https://atorrescode.github.io/dwes/
# docs_dir: md
# site_dir: docs
theme:
   name: 'material'
   features:
    - navigation.sections
    - navigation.top
    - content.code.copy
   font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
   icon:
    repo: 'fontawesome/brands/github'
   palette:
    - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
   logo: assets/img/pato_logo_3d.ico
   favicon: assets/img/favicon.ico

nav:
    - Home: index.md
    - Unidad 1. Introducción al desarrollo web:
      - 1. Arquitecturas web servidor: u01-introduccion-desarrollo-web/r01-arquitecturas-web-servidor.md
      - A1. Actividades: u01-introduccion-desarrollo-web/a01.md
    - Unidad 2. Introducción a PHP:
      - 1. Introducción a PHP: u02-introduccion-php/r01.md
      - A1. Actividades: u02-introduccion-php/a01.md
      - A2. Actividades de refuerzo: u02-introduccion-php/a02-refuerzo.md
      - A3. Actividades de ampliación: u02-introduccion-php/a03-ampliacion.md
    - Unidad 3. Generación dinámica y plantillas: u03/index.md
    - Unidad 4. Formularios, estado y sesiones: u04/index.md
    - Unidad 5. Arquitectura MVC y separación de lógica: u05/index.md
    - Unidad 6. Acceso a bases de datos y CRUD: u06/index.md
    - Unidad 7. Servicios Web y APIs REST: u07/index.md
    - Unidad 8. Integración con cliente y aplicaciones híbridas: u08/index.md
    - Unidad 9. Proyecto final y despliegue: u09/index.md
extra_css:
  - assets/css/style.css
extra_templates:
plugins:
  - search
  # - with-pdf
  # - pdf-export:
  #     combined: true
  # - page-to-pdf
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.embed