site_name: Desarrollo Web en Entorno Servidor
site_url: https://atorrescode.github.io/dwes/
# docs_dir: md
# site_dir: docs
theme:
   name: 'material'
   features:
    - navigation.sections
    - navigation.top
    - content.code.copy
   font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
   icon:
    repo: 'fontawesome/brands/github'
   palette:
    - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
   logo: img/pato_logo_3d.ico
   favicon: img/favicon.ico

nav:
    - Home: index.md
    - UF01. Introducción al desarrollo web:
      - R1.1. Arquitecturas web servidor: u01/r1.1.md
      - A1.1. Actividades: u01/a1.1.md
    - UF02. Introducción a PHP: u02/index.md
    - UF03. Generación dinámica y plantillas: u03/index.md
    - UF04. Formularios, estado y sesiones: u04/index.md
    - UF05. Arquitectura MVC y separación de lógica: u05/index.md
    - UF06. Acceso a bases de datos y CRUD: u06/index.md
    - UF07. Servicios Web y APIs REST: u07/index.md
    - UF08. Integración con cliente y aplicaciones híbridas: u08/index.md
    - UF09. Proyecto final y despliegue: u09/index.md
extra_css:
  - css/style.css
extra_templates:
plugins:
  - search
  # - with-pdf
  # - pdf-export:
  #     combined: true
  # - page-to-pdf
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.embed